name: Tic-Tac-Toe CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default qt5-qmake build-essential

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build application
      working-directory: ./app
      run: |
        qmake
        make

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and run tests
      run: |
        qmake TicTacToe_With_Tests.pro CONFIG+=test
        make
        cd tests
        ./tst_tictactoetests

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build release version
      working-directory: ./app
      run: |
        qmake
        make

    - name: Package application
      run: |
        mkdir -p release
        cp app/tictactoe release/
        tar -czvf tictactoe-release-${{ github.sha }}.tar.gz -C release tictactoe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-${{ github.sha }}
        name: Tic-Tac-Toe Release ${{ github.sha }}
        files: tictactoe-release-${{ github.sha }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
