name: Qt Build and Test (with Xvfb)

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Qt and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools g++ xvfb

    - name: 🔧 Build both app and tests using qmake
      run: |
        qmake TicTacToe_With_Tests.pro
        make -j2

    - name: 🧪 Run Qt Tests in Virtual Display (Xvfb)
      run: |
        chmod +x tests/tests
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./tests/tests -exitcode
