name: Tic-Tac-Toe Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    - name: Build application (debug)
  run: |
    set -euxo pipefail
    echo "Current directory:"
    pwd
    echo "Files in root:"
    ls -la
    echo "Running qmake..."
    qmake app.pro
    echo "Running make..."
    make VERBOSE=1
    echo "Files after make:"
    ls -la
    echo "All executables:"
    find . -type f -executable -ls
