#include <QtTest/QtTest>
#include "GameLogic.h"

class GameLogicTest : public QObject {
  Q_OBJECT

private slots:
  void testWinDetection() {
    // your test case
  }
};

QTEST_MAIN(GameLogicTest)
#include "test_main.moc"
