name: Qt Test Only

on:
  push:
  pull_request:

jobs:
  qt-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools g++

    - name: Build Test Binary
      run: |
        qmake tests.pro
        make -j2

    - name: Run Tests
      run: |
        chmod +x tests
        ./tests -exitcode
