name: C++ CI/CD with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: azyobuzin/setup-cmake@v1
      with:
        # Specify the version of CMake you need, e.g., '3.28.0'
        # If not specified, the latest version will be used.
        version: 'latest' 

    - name: Configure CMake
      # This step creates the build directory and generates the build files.
      # For Windows, it will default to Visual Studio generators.
      # For Linux, it will default to Makefiles.
      run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}

    - name: Build project
      # This step compiles your project using the generated build files.
      run: cmake --build ${{ github.workspace }}/build

    - name: Run tests
      # This step executes the tests. It assumes you have defined tests
      # with CTest as part of your CMake configuration.
      working-directory: ${{ github.workspace }}/build
      run: ctest -C Debug --output-on-failure
