name: Qt Build and Test (Optimized)

on:
  push:
  pull_request:

jobs:
  qt-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev qtchooser g++ xvfb

    - name: 🔧 Build tests only
      run: |
        cd tests
        qmake tests.pro
        make -j2

    - name: 🧪 Run Qt tests in virtual display
      run: |
        cd tests
        chmod +x tests
        timeout 60s xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./tests -exitcode
