name: Qt Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Qt and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools g++ xvfb

    - name: 🔧 Build using qmake and make
      run: |
        qmake TicTacToe_With_Tests.pro
        make
      timeout-minutes: 5

    - name: 🧪 Run Qt Tests (Headless)
      run: |
        chmod +x tests
        xvfb-run ./tests -exitcode -v || true
      timeout-minutes: 2
