name: Fast Qt Test CI

on:
  push:
  pull_request:

jobs:
  qt-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt and Xvfb (Minimal)
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev qtchooser g++ xvfb

    - name: 🔧 Build tests only
      run: |
        cd tests
        qmake tests.pro
        make -j2

    - name: 🧪 Run Qt tests (with timeout)
      run: |
        cd tests
        chmod +x tests
        timeout 60s xvfb-run --auto-servernum ./tests -exitcode
