name: CI/CD Pipeline for Tic-Tac-Toe

# Add permissions for the workflow
permissions:
  contents: write  # Required for creating releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Qt and dependencies
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default qt5-qmake build-essential

    # Step 3: Configure and build the project
    - name: Build the project
      run: |
        qmake TicTacToe_With_Tests.pro
        make

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Qt and dependencies
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default qt5-qmake build-essential

    # Step 3: Build the project (including tests)
    - name: Build the project
      run: |
        qmake TicTacToe_With_Tests.pro CONFIG+=test
        make

    # Step 4: Run the unit tests
    - name: Run unit tests
      run: |
        ./Tests/app/TicTacToeTests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Only deploy on push to main

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Qt and dependencies
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default qt5-qmake build-essential

    # Step 3: Configure and build the project
    - name: Build the project
      run: |
        qmake TicTacToe_With_Tests.pro
        make

    # Step 4: Package the binary
    - name: Package the binary
      run: |
        mkdir -p release
        cp TicTacToe_With_Tests release/
        tar -czvf tictactoe-${{ github.sha }}.tar.gz -C release TicTacToe_With_Tests

    # Step 5: Create a GitHub Release and upload the artifact
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-${{ github.sha }}
        name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        files: tictactoe-${{ github.sha }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
