name: Tic-Tac-Toe Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Qt (qmake)
        run: sudo apt-get update && sudo apt-get install -y qt5-qmake qtbase5-dev

      - name: Verify Qt installation
        run: |
          qmake --version
          which qmake

      - name: Build application
        run: |
          set -e
          echo "::group::Run qmake"
          qmake app.pro
          echo "::endgroup::"
          echo "::group::Run make"
          make VERBOSE=1
          echo "::endgroup::"
          echo "::group::List all files after build"
          ls -la
          echo "::endgroup::"
          echo "::group::Find all executables"
          find . -type f -executable
          echo "::endgroup::"
          # Check for expected output (edit 'tictactoe' if your binary name is different)
          if [ ! -f "tictactoe" ]; then
            echo "Error: Build failed - executable not found!"
            exit 1
          fi

      - name: Show build artifacts
        run: ls -la
