name: Qt Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout Repository
      uses: actions/checkout@v3

    - name:  Install Qt (qmake version)
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools g++

    - name: 🔧 Build using qmake and make
      run: |
        qmake TicTacToe_With_Tests.pro
        make

    - name: 🧪 Run Qt Tests
      run: |
        chmod +x tests
        ./tests -exitcode
